# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: param1
    displayName: vmName
    type: string
    default: $(param1)
  - name: param2
    displayName: adminUsername
    type: string
    default: $(param2)
  - name: param3
    displayName: adminPassword
    type: string
    default: $(param3)
  - name: param4
    displayName: location
    type: string
    default: $(param4)
  - name: param5
    displayName: Applications
    type: string
    default: $(param5)
  - name: param12
    displayName: System
    type: string
    default: $(param12)
  - name: param6
    displayName: Site
    type: string
    default: $(param6)
  - name: param7
    displayName: Department
    type: string
    default: $(param7)
  - name: param8
    displayName: Country
    type: string
    default: $(param8)
  - name: param9
    displayName: Owner
    type: string
    default: $(param9)
  - name: param10
    displayName: ResourceType
    type: string
    default: $(param10)
  - name: param11
    displayName: ResourceName
    type: string
    default: $(param11)
  - name: param12
    displayName: numberOfDataDisks
    type: string
    default: $(param12)   

trigger: 
      branches:
        include: 
        - none
        
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self

              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '#TODO'
                  subscriptionId: '#TODO'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '#TODO'
                  location: 'eastus'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/azuredeploy.parameters.json'
                  deploymentMode: Incremental
                  overrideParameters: "-vmName ${{parameters.param1}} 
                  -adminUsername ${{parameters.param2}} 
                  -adminPassword ${{parameters.param3}} 
                  -location ${{parameters.param4}} 
                  -Applications ${{parameters.param5}} 
                  -System ${{parameters.param5}} 
                  -Site ${{parameters.param6}} 
                  -Department ${{parameters.param7}} 
                  -Country ${{parameters.param8}} 
                  -Owner ${{parameters.param9}} 
                  -ResourceType ${{parameters.param10}} 
                  -ResourceName ${{parameters.param11}} 
                  -numberOfDataDisks ${{parameters.param12}}"

