# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: param1
    displayName: vmName
    type: string
    default: $(param1)
  - name: param2
    displayName: adminUsername
    type: string
    default: $(param2)
  - name: param3
    displayName: adminPassword
    type: string
    default: $(param3)
  - name: param4
    displayName: location
    type: string
    default: $(param4)
  - name: param8
    displayName: resourceTags
    type: string
    default: $(param8)

trigger: 
      branches:
        include: 
        - none
        
stages :        
  - stage: arm_template_deploy
    jobs:
      - job: arm_template_deploy
        steps:
              - checkout: self

              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'PowerAppsSPN'
                  subscriptionId: '903d847b-78e2-4a91-a151-7e2295a32f1d'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: 'PowerApps'
                  location: 'eastus'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
                  csmParametersFile: '$(System.DefaultWorkingDirectory)/azuredeploy.parameters.json'
                  overrideParameters: -vmName ${{parameters.param1}} -adminUsername ${{parameters.param2}} -adminPassword ${{parameters.param3}} -location ${{parameters.param4}} -resourceTags ${{parameters.param8}}
                  deploymentMode: Incremental

